/**
 * Pure helpers for turning a pre-rendered narration manifest (see
 * scripts/generate-narration.mjs) into something useAudioNarration can
 * play, plus the integrity check that protects against a stale manifest
 * silently narrating the wrong words after a story edit.
 *
 * A manifest entry is generated per node as an array aligned 1:1, in
 * order, with buildSpeechQueue(node) (textSegments.js) — the same
 * function both this app and the generation script call, so "segment 3"
 * always means the same thing in both places. Each entry is
 * { base: 'relative/path.mp3', char?: 'relative/path.mp3' }: `base` is
 * always Adam Stone (every segment, narrator and dialogue alike, since
 * that's the toggle-off fallback track); `char` exists only for
 * dialogue segments and holds that title's cast-voice take.
 */

export function manifestUrlFor(titleId) {
  return `/narration/${titleId}/manifest.json`;
}

/**
 * True only for a manifest generated by the real `elevenlabs` backend —
 * false for the `silence` backend (ffmpeg placeholder tones used only to
 * test the toggle/plumbing during development) and for no manifest at
 * all. There is no reader-facing narration UI for a title until this is
 * true: readers never see the placeholder tones, and never fall back to
 * the browser's speechSynthesis voices either — see useAudioNarration's
 * `available` and App.jsx's `narrationAvailable`.
 */
export function isRealNarrationBackend(backend) {
  return backend === 'elevenlabs';
}

export function audioUrlFor(titleId, relPath) {
  return `/narration/${titleId}/${relPath}`;
}

/**
 * True only if a manifest's entries for a node line up 1:1 with what the
 * story would actually queue up to speak right now. A story edit that
 * adds/removes a line after audio was generated makes this false — the
 * caller should treat that node as having no pre-rendered audio at all
 * rather than play badly-misaligned narration.
 */
export function manifestMatchesQueue(entries, queue) {
  return Array.isArray(entries) && Array.isArray(queue) && entries.length === queue.length;
}

/**
 * Zips a speech queue (from buildSpeechQueue) with its manifest entries
 * into a playable queue of { speaker, text, src }, honoring the
 * multi-voice toggle: character segments get their cast-voice clip only
 * when `multiVoice` is on and that clip actually exists; everything else
 * (narrator segments always, character segments when the toggle is off
 * or no character clip was rendered) falls back to the Adam Stone base
 * clip. Returns null when the manifest doesn't match this queue (see
 * manifestMatchesQueue) so the caller can fall back to another
 * narration backend instead of playing misaligned audio.
 */
export function buildAudioQueue(titleId, queue, entries, multiVoice) {
  if (!manifestMatchesQueue(entries, queue)) return null;

  const result = [];
  for (let i = 0; i < queue.length; i += 1) {
    const entry = entries[i] || {};
    const relPath = (multiVoice && entry.char) ? entry.char : entry.base;
    if (!relPath) return null; // a segment with no usable clip at all — treat the whole node as unavailable
    result.push({ speaker: queue[i].speaker, text: queue[i].text, src: audioUrlFor(titleId, relPath) });
  }
  return result;
}
